#!/usr/bin/python

from wsgiref.simple_server import make_server
from exceptions import Exception, KeyboardInterrupt
from py_compile import compile
from signal import signal, SIGTERM
from socket import error as SocketError, getfqdn
from ConfigParser import ParsingError
from traceback import format_exception

import sys, os

from phttp.util import usage, configure, save_pid

def sigterm(sig, stack = None):
    env.log.error('[S] Shotdown server signal(%s)' % sig)
    os.unlink(pidfile)
    sys.exit()
#enddef

try:
    cfg = configure()
    pidfile = save_pid()

    signal(SIGTERM, sigterm)
    
    from phttp import env, handlers
    from phttp.enums import *
    from phttp.classes import WebRequestHandler, PoorServerHandler
    from phttp.importing import *
    
    env.server_address = cfg.get('http', 'address')
    env.server_port = cfg.getint('http', 'port')
    env.server_host = getfqdn(env.server_address)
    
    env.log.error('[S] Starting server type %s at %s:%s' \
            % (env.server_class.type, env.server_address, env.server_port))

    exec ("from %s import application" % os.environ['poor.Application']) in globals()
    httpd = make_server(env.server_address,
                        env.server_port,
                        application,
                        server_class = env.server_class,
                        handler_class = WebRequestHandler
                        )
    #print ""
    #print "%s:%s\n" % (WebRequestHandler, dir(WebRequestHandler))
    #print "%s:%s\n" % (PoorServerHandler, dir(PoorServerHandler))
    #print "%s:%s\n" % (Request, dir(Request))
    httpd.timeout = 0.5
    httpd.serve_forever()
except KeyboardInterrupt, e:
    env.log.error('[S] Shotdown server (keyboard interrupt)')
    del(env.log)
    os.unlink(pidfile)
except SocketError, e:
    env.log.error("[S] %s" % e[1])
    del(env.log)
    os.unlink(pidfile)
    sys.exit(1)
except ParsingError, e:
    # configure error
    usage("Exception: %s" % e.message)
    del(env.log)
    sys.exit(1)
except os.error, e:
    # pid error
    usage("Exception: %s" % e)
    del(env.log)
    sys.exit(1)
except Exception, e:
    traceback = format_exception(sys.exc_type,
                                 sys.exc_value,
                                 sys.exc_traceback)
    traceback = ''.join(traceback)
    usage("Exception: %s" % traceback)
    del(env.log)
    os.unlink(pidfile)
    sys.exit(1)
#endtry
