#!/bin/sh

poorhttp=/srv/poorhttp/poorhttp
pidfile=/srv/run/poorhttp.pid
config=/srv/etc/poorhttp.ini

case "$1" in
    start)
        if [ -f $pidfile ]; then
            $0 stats
        else
            echo -n "Starting Poor Http server ... "
            $poorhttp --pidfile=$pidfile --config=$config &
            sleep 1
            if [ -f $pidfile ]; then
                echo "Ok"
            else
                echo "Failed"
                exit 1
            fi
        fi
        ;;
    stop)
        if [ -f $pidfile ]; then
            echo "Stoping Poor Http server ..."
            kill `cat $pidfile`
        else
            echo "Poor Http is shutdown"
        fi
        ;;
    stats)
        if [ -f $pidfile ]; then
            pid=`cat $pidfile`
            echo "Poor Http is running: $pid"
        else
            echo "Poor Http is shutdown"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|stats|restart}"
        exit 1
        ;;
esac

exit 0
